name: 'SWM GitHub Actions Basic'

on: push
env:
  GLOBAL_LEVEL: "GLOBAL level" 
jobs:
  first-job:
    name: 'First Job'

    runs-on: ubuntu-latest
    env:
      JOB_LEVEL_1: "JOB level1"

    steps:
    - name: Say Hello World 1
      shell: bash
      env:
        STEP_LEVEL_1: "STEP level"
      run: |
        echo "Hello World from step 1"
        echo "GLOBAL : Hello world from ${{env.GLOBAL_LEVEL}}"
        echo "JOB 1 : Hello world from ${{env.JOB_LEVEL_1}}"
        echo "JOB 2 : Hello world from ${{env.JOB_LEVEL_2}}"
        echo "STEP 1 : Hello world from ${{env.STEP_LEVEL_1}}"
        echo "STEP 2 : Hello world from ${{env.STEP_LEVEL_2}}"

    - name: Say Hello World 2
      shell: pwsh
      env:
        STEP_LEVEL_2: "STEP leve2"
      run: |
        echo "Hello World from step 2"
        echo "GLOBAL : Hello world from ${{env.GLOBAL_LEVEL}}"
        echo "JOB 1 : Hello world from ${{env.JOB_LEVEL_1}}"
        echo "JOB 2 : Hello world from ${{env.JOB_LEVEL_2}}"
        echo "STEP 1 : Hello world from ${{env.STEP_LEVEL_1}}"
        echo "STEP 2 : Hello world from ${{env.STEP_LEVEL_2}}"
  second-job:
    name: 'Second Job'

    runs-on: ubuntu-latest
    env:
      JOB_LEVEL_2: "JOB level2"
    steps:
    - name: Say Hello World 1
      shell: bash
      env:
        STEP_LEVEL_1: "STEP level"
      run: |
        echo "Hello World from step 1"
        echo "GLOBAL : Hello world from ${{env.GLOBAL_LEVEL}}"
        echo "JOB 1 : Hello world from ${{env.JOB_LEVEL_1}}"
        echo "JOB 2 : Hello world from ${{env.JOB_LEVEL_2}}"
        echo "STEP 1 : Hello world from ${{env.STEP_LEVEL_1}}"
        echo "STEP 2 : Hello world from ${{env.STEP_LEVEL_2}}"

    - name: Say Hello World 2
      shell: pwsh
      env:
        STEP_LEVEL_2: "STEP leve2"
      run: |
        echo "Hello World from step 2"
        echo "GLOBAL : Hello world from ${{env.GLOBAL_LEVEL}}"
        echo "JOB 1 : Hello world from ${{env.JOB_LEVEL_1}}"
        echo "JOB 2 : Hello world from ${{env.JOB_LEVEL_2}}"
        echo "STEP 1 : Hello world from ${{env.STEP_LEVEL_1}}"
        echo "STEP 2 : Hello world from ${{env.STEP_LEVEL_2}}"