name: 'SWM GitHub Actions Basic'

on: push

jobs:
  first-job:
    name: 'First Job'

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Send message to Webex space
      shell: bash
      run: |
        curl --location --request POST 'https://webexapis.com/v1/messages' \
        --header 'Authorization: Bearer ${{ secrets.WEBEX_TOKEN }}' \
        --header 'Content-Type: application/json' \
        --data-raw '{
          "roomId": "${{ secrets.WEBEX_ROOM_ID }}",
          "text": "curl 명령어를 사용한 깃헙 액션 워크샵입니다 - nh from ${{ github.repository }}"
        }'

    - name: Post Message to Webex Room
      uses: chrivand/action-webex-js@main # 가져다 쓰겠다
      env:
        WEBEX_TOKEN: ${{ secrets.WEBEX_TOKEN }}
        WEBEX_ROOM_ID: ${{ secrets.WEBEX_ROOM_ID }}
        MARKDOWN_MESSAGE: "**마켓플레이스에서 검색한 액션으로 보내는 깃헙 액션 워크샵입니다 - nh from ${{ github.repository }}.**"

    - name: Send message to Webex
      uses: ./.github/actions # 우리꺼
      with: # parameter라는 의미
        webexToken: ${{secrets.WEBEX_TOKEN}}
        webexRoomId: ${{secrets.WEBEX_ROOM_ID}}
        bodyText: "커스텀 액션을 사용한 깃헙 액션 워크샵입니다 - nh from ${{ github.repository }}"
