## 매트릭스 사용하기 ## 
# job 하나에 OS는 하나만 붙는다
name: 'SWM GitHub Actions Basic'

on: push

jobs:
  first-job:
    name: 'First Job'

    strategy:
      matrix:
        os: [ 'windows-latest', 'macos-latest', 'ubuntu-latest' ]
        nodejs: ['16.x','18.x'] # nodejs버젼 이 두개를 다 돌리고 싶으면?
    runs-on: ${{ matrix.os }}

    steps:
    - name: Say Hello World on ${{ matrix.os }}
      shell: bash
      run: |
        echo "Hello World on ${{ matrix.os }} with ${{matrix.nodejs}}"
        
    - name: Say Hello World on ${{ matrix.os }}
      if: matrix.os == 'ubuntu_latest'
      shell: bash
      run: |
        echo "Hello World on ${{ matrix.os }} with ${{matrix.nodejs}}"       